<CustomDropDown>

    Button:
        id: Button
        text: 'Press'
        size_hint_y: None
        height: '50dp'
        on_release: dropdown.open(self)
        DropDown:
            id: dropdown
            Button:
                text: 'First Item'
                size_hint_y: None
                height: '50dp'

            Button:
                text: 'second Item'
                size_hint_y: None
                height: '50dp'
